feat: added wrapper function for GetStructFromInchI function
manufac-analytics/inchi pull request #19
Opened 2021-08-23 10:02 UTC by qur786

@maneetgoyal sir , can you look at the GetStructFromINCHI wrapper function , in which the ref( ) is not working with inchi_InputINCHI and inchi_OutputStruct . I don't know why

2021-08-23 10:24 UTC, maneetgoyal requested changes
> can you look at the GetStructFromINCHI wrapper function , in which the ref( ) is not working with inchi_InputINCHI and inchi_OutputStruct on line no 113 . I don't know why

Will try to check in a bit

2021-08-23 10:24 UTC, maneetgoyal commented on src/api.ts
> +  const Output =  INCHIAPI.GetStructFromINCHI(inchiIn.ref(),inchiOutStruct.ref());
Code isnt prettified.

2021-08-23 10:24 UTC, maneetgoyal commented on src/api.ts
> +export function GetStructFromINCHI(input: string,options: string[] = [""]):0 | -1 | -2 | 1 | 2 | 3 | 4 | 5 {
Declare `0 | -1 | -2 | 1 | 2 | 3 | 4 | 5` as a union type and then reuse it.

Do the same for `0 | -1 | 1 | 2 | 3 | 4` and `0 | -1 | 1 | 2 | 3`.

2021-08-23 10:37 UTC, qur786 commented
@maneetgoyal  sure sir

2021-08-23 11:02 UTC, maneetgoyal requested changes
Casing issues.

2021-08-23 11:02 UTC, maneetgoyal commented on src/api.ts
> +type returnTypeCheckINCHIKey = 0 | -1 | 1 | 2 | 3;
Type should be PascalCased and should all be declared together.

2021-08-23 11:02 UTC, maneetgoyal commented on src/api.ts
> +  const Output = INCHIAPI.GetStructFromINCHI(inchiIn.ref(), inchiOutStruct.ref());
Variable should be camelCased.

2021-08-23 11:57 UTC, maneetgoyal requested changes

2021-08-23 11:57 UTC, maneetgoyal commented on src/api.ts
> +type ReturnTypeCheckINCHIKey = 0 | -1 | 1 | 2 | 3;
As mentioned before, all the types should be declared together in a group:

```ts
type ReturnTypeCheckINCHIKey = 0 | -1 | 1 | 2 | 3;
type ReturnTypeCheckINCHI = 0 | -1 | 1 | 2 | 3 | 4;
...
```

2021-08-24 03:28 UTC, maneetgoyal commented on src/api.ts
> +  }
Create a function to modularize this logic.

2021-08-24 03:30 UTC, maneetgoyal requested changes

2021-08-24 03:30 UTC, maneetgoyal commented on src/api.ts
> +  inchiInputObj.szOptions = optionString;
```suggestion
  const inchiInputObj = { szInChI: input, szOptions: optionString };
```

2021-08-24 03:30 UTC, maneetgoyal commented on src/api.ts
> +  inchiInputObj.szOptions = optionString;
```suggestion
  const inchiInputObj = { szInChI: input, szOptions: optionString };
```

2021-08-24 03:30 UTC, maneetgoyal commented on src/api.ts
> +  const optionString = generateOptionsString(inputInchiOptions);
```ts
const optionString = generateOptionsString(inputInchiOptions);
```

This line can also go inside the new function.

2021-08-24 03:37 UTC, qur786 commented
sure sir

2021-08-24 07:34 UTC, maneetgoyal commented
@qur786 What updates do you have here?

2021-08-24 07:39 UTC, maneetgoyal commented on src/api.ts
> +   */
@qur786 Similar to the other comments, add comments for all the option `keys`.

2021-08-24 07:45 UTC, maneetgoyal commented on src/api.ts
> +   * Error: no InChI has been created
@qur786 Similar to this object, create objects for `StatusReturnType1` and `StatusReturnType2` too.

2021-08-24 09:54 UTC, maneetgoyal commented
Also add unit test cases in a new file (`tests/api.test.ts`) for all these exposed functions.

2021-08-24 15:04 UTC, qur786 commented
a lot of mistakes on issue history .

2021-08-24 15:04 UTC, closed without merging