modify type definition in headers.ts
manufac-analytics/inchi pull request #38
Opened 2021-08-31 08:17 UTC by qur786

@maneetgoyal  Sir , I have updated some type definition , and I have already updated rest of the definition in object Dereference .

2021-08-31 10:48 UTC, maneetgoyal commented
Will look after #33 is tackled

2021-09-02 17:52 UTC, maneetgoyal commented
Lets try to fix this before #25

2021-09-02 17:54 UTC, qur786 commented
> Lets try to fix this before #25

Sir actually I am waiting a review from you .

2021-09-02 18:10 UTC, maneetgoyal commented
There was merge conflict so didn't review. Will start in a bit now.

2021-09-02 18:12 UTC, maneetgoyal requested changes

2021-09-02 18:12 UTC, maneetgoyal commented on src/headers.ts
> +  stereo0D: NAPIArrayType(inchi_Stereo0D),
Why is it reverted?

2021-09-02 18:12 UTC, maneetgoyal commented on src/headers.ts
> +  v3000: NAPIArrayType(inchi_Input_V3000),
Revert this change

2021-09-02 18:12 UTC, maneetgoyal commented on src/headers.ts
> +  at_fixed_bonds: NAPIArrayType(NORM_ATOM),
You may need to revert this chnage, please check and confirm

2021-09-02 18:12 UTC, maneetgoyal commented on tests/headers.test.ts
> +    expect(inchiInputEx.v3000[0].n_non_star_atoms).toBe(0);
Revert the chnage

2021-09-03 10:22 UTC, maneetgoyal reviewed
Minor

2021-09-03 10:22 UTC, maneetgoyal commented on src/headers.ts
> +export const MAXARRAYSIZE = 999; // to create array with huge size
```suggestion
export const MAX_ARRAY_SIZE = 999; // to create array with huge size
```

2021-09-03 10:22 UTC, maneetgoyal commented on src/headers.ts
> +  // sir , look at below two key deifintion , should it be as it is or i have to change it to an array from pointer
```suggestion
```

Looks okay.

2021-09-03 10:50 UTC, qur786 commented
there is some problem with stereo0D sir , in the last commit I have wrote some comments about it , please check it @maneetgoyal sir

2021-09-03 11:16 UTC, maneetgoyal approved these changes
👍

2021-09-03 11:17 UTC, maneetgoyal commented
> there is some problem with stereo0D sir , in the last commit I have wrote some comments about it , please check it @maneetgoyal sir

@qur786 Should be fixed now

2021-09-03 11:36 UTC, qur786 commented
> > there is some problem with stereo0D sir , in the last commit I have wrote some comments about it , please check it @maneetgoyal sir
> 
> @qur786 Should be fixed now

yes sir

2021-09-03 11:39 UTC, merged